import attachments.Attachment

data class Post(
    val id: Int = 0,
    val ownerId: Int = 0,
    val fromId: Int = 0,
    val createdBy: Int = 0,
    val date: Int = 0,
    val text: String = "",
    val replyOwnerId: Int = 0,
    val replyPostId: Int = 0,
    val friendsOnly: Boolean = false,
    val comments: Comments = Comments(0,true,true,true,true),
    val copyright: Copyright = Copyright(0,"","",""),
    val likes: Likes = Likes(0,true,true,true),
    val reposts: Reposts = Reposts(0,false),
    val views: Views = Views(0),
    val postType: String = "",
    val postSource: PostSource = PostSource(""),
    val geo: Geo = Geo("","", null),
    val signerId: Int = 0,
    val canPin: Boolean = true,
    val canDelete: Boolean = true,
    val canEdit: Boolean = true,
    val isPinned: Boolean = false,
    val markedAsAds: Boolean = false,
    val isFavorite: Boolean = false,
    val donut: Donut = Donut(false,0,null,true,"All"),
    val postponedId: Int? = null,
    val attachments: Array<Attachment>? = null
)